// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    var $canvas, $text, draw, drawWrapper, processingInstance;
    $text = $("#texts");
    $canvas = $("#renderings");
    processingInstance = null;
    draw = function() {
      var texts, value;
      value = $text.val();
      texts = value.split(/\r\n|\r|\n/);
      return processingInstance = app.wordshapeMulti(texts, $canvas);
    };
    drawWrapper = function(evt) {
      return draw();
    };
    $("#multiDrawBtn").click(drawWrapper);
    return $text.focus();
  });

}).call(this);
