// Generated by CoffeeScript 1.4.0
(function() {

  app.wordshapeSketch = function(text, width, height, fill, color) {
    if (width == null) {
      width = 800;
    }
    if (height == null) {
      height = 373;
    }
    if (fill == null) {
      fill = true;
    }
    if (color == null) {
      color = 0;
    }
    return function(processing) {
      var coordinates;
      coordinates = app.string2coords(app.LAYOUTS["QWERTY"], app.EXCLUDES, text);
      processing.setup = function() {
        processing.size(width, height);
        return processing.background(255);
      };
      return processing.draw = function() {
        var coord, _i, _len;
        if (fill) {
          processing.fill(color);
        }
        processing.beginShape();
        for (_i = 0, _len = coordinates.length; _i < _len; _i++) {
          coord = coordinates[_i];
          processing.vertex(coord[0], coord[1]);
        }
        processing.endShape(processing.CLOSE);
        return processing.noLoop();
      };
    };
  };

  app.wordshape = function(text, canvas) {
    var height, processingInstance, width;
    height = canvas.offsetHeight;
    width = canvas.offsetWidth;
    return processingInstance = new Processing(canvas, app.wordshapeSketch(text, width, height));
  };

  app.wordshapeMulti = function(texts, parent) {
    var $rendering, canvas, height, processingInstance, text, width, _i, _len, _results;
    height = 373;
    width = 800;
    parent.empty();
    _results = [];
    for (_i = 0, _len = texts.length; _i < _len; _i++) {
      text = texts[_i];
      if (!text) {
        continue;
      }
      text = text.trim();
      $rendering = $("<div class='rendering'><div class='text'>" + text + "</div><canvas style=\"height:" + height + "px; width:" + width + "px;\"></canvas></div>");
      $rendering.appendTo(parent);
      canvas = $("canvas", $rendering)[0];
      _results.push(processingInstance = new Processing(canvas, app.wordshapeSketch(text, width, height)));
    }
    return _results;
  };

}).call(this);
