// Generated by CoffeeScript 1.4.0
(function() {

  app.wordshapeSketch = function(text, width, height, fill, color) {
    if (width == null) {
      width = 800;
    }
    if (height == null) {
      height = 373;
    }
    if (fill == null) {
      fill = true;
    }
    if (color == null) {
      color = 0;
    }
    return function(processing) {
      var coordinates;
      coordinates = app.string2coords(app.LAYOUTS["QWERTY"], app.EXCLUDES, text);
      processing.setup = function() {
        processing.size(width, height);
        return processing.background(255);
      };
      return processing.draw = function() {
        var coord, _i, _len;
        if (fill) {
          processing.fill(color);
        }
        processing.beginShape();
        for (_i = 0, _len = coordinates.length; _i < _len; _i++) {
          coord = coordinates[_i];
          processing.vertex(coord[0], coord[1]);
        }
        processing.endShape(processing.CLOSE);
        return processing.noLoop();
      };
    };
  };

  app.wordshape = function(text, canvas) {
    var height, processingInstance, width;
    height = canvas.offsetHeight;
    width = canvas.offsetWidth;
    return processingInstance = new Processing(canvas, app.wordshapeSketch(text, width, height));
  };

}).call(this);
