// Generated by CoffeeScript 1.4.0
(function() {

  app.wordshapeSketch = function(text, width, height, fill, color, scale) {
    if (width == null) {
      width = 800;
    }
    if (height == null) {
      height = 373;
    }
    if (fill == null) {
      fill = true;
    }
    if (color == null) {
      color = 0;
    }
    if (scale == null) {
      scale = 1.0;
    }
    return function(processing) {
      var coordinates;
      coordinates = app.string2coords(app.LAYOUTS["QWERTY"], app.EXCLUDES, text);
      processing.setup = function() {
        processing.size(width, height);
        return processing.background(255);
      };
      return processing.draw = function() {
        var coord, _i, _len;
        if (fill) {
          processing.fill(color);
        }
        processing.scale(scale);
        processing.beginShape();
        for (_i = 0, _len = coordinates.length; _i < _len; _i++) {
          coord = coordinates[_i];
          processing.vertex(coord[0], coord[1]);
        }
        processing.endShape(processing.CLOSE);
        processing.noLoop();
        return $(document).trigger('drawFinished');
      };
    };
  };

  app.wordshape = function(text, canvas) {
    var height, width;
    height = canvas.offsetHeight;
    width = canvas.offsetWidth;
    return new Processing(canvas, app.wordshapeSketch(text, width, height));
  };

  app.wordshapeMulti = function(texts, parent) {
    var $canvas, $rendering, height, processingInstance, text, width, _fn, _i, _len;
    height = 373;
    width = 800;
    texts = texts.filter(function(x) {
      return x.trim();
    });
    _fn = function(processingInstance) {
      return $canvas.click(function(e) {
        return processingInstance.save('text.png');
      });
    };
    for (_i = 0, _len = texts.length; _i < _len; _i++) {
      text = texts[_i];
      text = text.trim();
      $rendering = $("<div class='rendering span3'><div class='text'>" + text + "</div><canvas class='span3'></canvas></div>");
      $rendering.appendTo(parent);
      $canvas = $("canvas", $rendering);
      processingInstance = new Processing($canvas[0], app.wordshapeSketch(text, width, height));
      _fn(processingInstance);
    }
  };

}).call(this);
